name: 'Terraform PR'

on:
  # For testing
  # workflow_dispatch:
  # Real
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
      
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/terraform-main-infra

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          src/terraform-main-infra
          src/ansible

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "~>1.9.1"
        
    - name: Create authorized_key.json
      run: |
        cat > authorized_key.json << 'EOF'
        ${{ secrets.YC_AUTHORIZED_KEY }}
        EOF

    - name: Create backend.hcl
      run: |
        cat > backend.hcl << 'EOF'
        ${{ secrets.TERRAFORM_BACKEND }}
        EOF

    - name: Create personal.auto.tfvars
      run: |
        cat > personal.auto.tfvars << 'EOF'
        ${{ secrets.TERRAFORM_PERSONAL_VARS }}
        EOF

    - name: Create ssh public key file
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/id_ed25519.pub << 'EOF'
        ${{ secrets.SSH_PUBLIC_KEY }}
        EOF
        chmod 700 ~/.ssh
        chmod 644 ~/.ssh/id_ed25519.pub
        
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      env:
        YC_BACKEND_ACCESS_KEY: ${{ secrets.YC_BACKEND_ACCESS_KEY }}
        YC_BACKEND_SECRET_KEY: ${{ secrets.YC_BACKEND_SECRET_KEY }}
      run: |
        echo ::add-mask::$YC_BACKEND_ACCESS_KEY
        echo ::add-mask::$YC_BACKEND_SECRET_KEY
        terraform init -backend-config="access_key=${YC_BACKEND_ACCESS_KEY}" -backend-config="secret_key=${YC_BACKEND_SECRET_KEY}" -backend-config=backend.hcl

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false
    
    - name: Upload inventory.txt
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v7
      with:
        name: inventory.txt
        path: ${{ github.workspace }}/src/ansible/playbook/inventory/inventory.txt
        archive: false
    
    - name: Upload all.yaml
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v7
      with:
        name: all.yaml
        path: ${{ github.workspace }}/src/ansible/playbook/inventory/group_vars/all.yaml
        archive: false
