name: 'Terraform PR'

on:
  # For testing
  # workflow_dispatch:
  # Real
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    outputs:
      need_ansible: ${{ steps.plan.outputs.need_ansible }}

    defaults:
      run:
        shell: bash
        working-directory: ./src/terraform-main-infra

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          src/terraform-main-infra
          src/ansible

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
        terraform_version: "~>1.9.1"
        
    - name: Create authorized_key.json
      run: |
        cat > authorized_key.json << 'EOF'
        ${{ secrets.YC_AUTHORIZED_KEY }}
        EOF

    - name: Create backend.hcl
      run: |
        cat > backend.hcl << 'EOF'
        ${{ secrets.TERRAFORM_BACKEND }}
        EOF

    - name: Create personal.auto.tfvars
      run: |
        cat > personal.auto.tfvars << 'EOF'
        ${{ secrets.TERRAFORM_PERSONAL_VARS }}
        EOF

    - name: Create ssh public key files
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/vm_user.pub << 'EOF'
        ${{ secrets.SSH_PUBLIC_KEY_VM_USER }}
        EOF
        cat > ~/.ssh/cicd.pub << 'EOT'
        ${{ secrets.SSH_PUBLIC_KEY_CICD }}
        EOT
        chmod 700 ~/.ssh
        chmod 644 ~/.ssh/vm_user.pub
        chmod 644 ~/.ssh/cicd.pub
        cat > extra.tfvars << 'EOF'
        ssh_key_paths = ["~/.ssh/vm_user.pub", "~/.ssh/cicd.pub"]
        EOF
    
    - name: Terraform Init
      env:
        YC_BACKEND_ACCESS_KEY: ${{ secrets.YC_BACKEND_ACCESS_KEY }}
        YC_BACKEND_SECRET_KEY: ${{ secrets.YC_BACKEND_SECRET_KEY }}
      run: |
        echo ::add-mask::$YC_BACKEND_ACCESS_KEY
        echo ::add-mask::$YC_BACKEND_SECRET_KEY
        terraform init -backend-config="access_key=${YC_BACKEND_ACCESS_KEY}" -backend-config="secret_key=${YC_BACKEND_SECRET_KEY}" -backend-config=backend.hcl

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -var-file=extra.tfvars -out=plan.tfplan
        echo "need_ansible=false" >> $GITHUB_OUTPUT

        if terraform show -json plan.tfplan | jq -e '
          .resource_changes[]? |
          select(.change.actions | index("create") or index("update") or index("delete")) |
          select((.change.after.labels?["k8s"] != null))
        ' > /dev/null; then
          echo "need_ansible=true" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false plan.tfplan

    - name: Upload inventory.ini
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v7
      with:
        name: inventory.ini
        path: ${{ github.workspace }}/src/ansible/playbook/inventory/inventory.ini
        archive: false
    
    - name: Upload all.yaml
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v7
      with:
        name: all.yaml
        path: ${{ github.workspace }}/src/ansible/playbook/inventory/group_vars/all.yaml
        archive: false
  ansible:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.terraform.outputs.need_ansible == 'true'
    needs: terraform
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./src/ansible/playbook
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: src/ansible
      
      - name: Create ssh key files
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ed25519.pub << 'EOF'
          ${{ secrets.SSH_PUBLIC_KEY_CICD }}
          EOF
          cat > ~/.ssh/id_ed25519 << 'EOF'
          ${{ secrets.SSH_PRIVATE_KEY_CICD }}
          EOF
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          cat > ~/.ssh/config << 'EOF'
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF
      
      - name: Download all.yaml
        uses: actions/download-artifact@v8
        with:
          name: all.yaml
          path: ${{ github.workspace }}/src/ansible/playbook/inventory/group_vars/
      
      - name: Download inventory.ini
        uses: actions/download-artifact@v8
        with:
          name: inventory.ini
          path: ${{ github.workspace }}/src/ansible/playbook/inventory/

      - name: Check artifacts
        run: |
          cat inventory/inventory.ini
          cat inventory/group_vars/all.yaml
          
      - name: Create venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      
      - name: Install python requirements
        run: pip install -r venv_requirements.txt --quiet

      - name: Install ansible requirements
        run: ansible-galaxy install -r requirements.yaml
      
      - name: Add key to ssh agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519

      # Because Yandex Cloud VMs sometimes are not immediately available by SSH after the creation
      - name: Wait
        run: sleep 1m
      
      - name: Run kubespray
        run: ansible-playbook -i inventory/inventory.ini -b main.yaml
  kube:
    needs: ansible
    name: "k8s manifests"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout manifests
        uses: actions/checkout@v6
        with:
          repository: ritehist/devops-diploma-kube
          ref: 'main'
        
      - name: Download inventory.ini
        uses: actions/download-artifact@v8
        with:
          name: inventory.ini
      
      - name: Parse controller and NAT IPs
        id: ips
        run: |
          NAT_IP=$(awk '/\[bastion\]/ {flag=1; next} flag && /ansible_host=/ {gsub(/.*=/,""); print; flag=0}' inventory.ini)
          CONTROLLER_IP=$(awk '/\[kube_control_plane\]/ {flag=1; next} flag && /ansible_host=/ {gsub(/.*=/,""); print; flag=0}' inventory.ini)
          echo "nat_ip=$NAT_IP" >> $GITHUB_OUTPUT
          echo "controller_ip=$CONTROLLER_IP" >> $GITHUB_OUTPUT
        
      - name: Create ssh key file
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ed25519 << 'EOF'
          ${{ secrets.SSH_PRIVATE_KEY_CICD }}
          EOF
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          cat > ~/.ssh/config << 'EOF'
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF
      
      - name: Add key to ssh agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519

      - name: Copy admin.conf from controller
        env:
          NAT_IP: ${{ steps.ips.outputs.nat_ip }}
          CONTROLLER_IP: ${{ steps.ips.outputs.controller_ip }}
        run: |
          ssh -o ProxyJump=${{ vars.VM_USERNAME }}@${NAT_IP} ${{ vars.VM_USERNAME }}@${CONTROLLER_IP} "sudo cat /etc/kubernetes/admin.conf" > admin.conf
      
      - name: Change server in admin.conf
        env:
          NAT_IP: ${{ steps.ips.outputs.nat_ip }}
        run: |
          sed -i "s|server: https://[^:]*:6443|server: https://${NAT_IP}:6443|" admin.conf
      
      - name: Get admin.conf content
        id: kubeconfig
        run: |
          CONFIG_CONTENT=$(cat admin.conf | base64 -w 0)
          echo "::add-mask::$CONFIG_CONTENT"
          echo "kubeconfig=$CONFIG_CONTENT" >> $GITHUB_OUTPUT
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      
      - name: Set kube context
        uses: azure/k8s-set-context@v5
        with:
          method: kubeconfig
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
          kubeconfig-encoding: base64
      
      - name: Deploy app manifests
        uses: Azure/k8s-deploy@v5
        with:
          manifests: src/app-config/
          action: deploy
      
      - name: Install helm
        uses: azure/setup-helm@v5.0.0
        id: install
      
      - name: Install helm chart
        run: |
          helm upgrade --install monitoring -f src/kube-prometheus-stack/values.yaml oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack --create-namespace -n monitoring
      
      - name: Create grafana ingress
        run: |
          kubectl apply -f src/kube-prometheus-stack/grafana-ingress.yaml